language: bash

services: docker

addons:
  apt:
    packages:
      - wget

script: uname -a

matrix:
  include:
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:gcc-latest"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:gcc-7.2"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:gcc-6.4"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:gcc-5.5"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:gcc-4.9"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:gcc-4.8"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:gcc-4.6"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:gcc-4.4"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:clang-latest"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:clang-6.0"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:clang-5.0"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:clang-4.0"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:clang-3.8"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:clang-3.6"
    - env: DOCKER_IMAGE="yudonguk/bicomc-docker:clang-3.4"

