language: bash

services: docker

addons:
  apt:
    packages:
      - wget

dependencies:
  cache_directories:
    - docker

script: |
  bash -c "
  DOCKER_REPOSITORY=yudonguk/bicomc-docker;
  DOCKER_TAGS=$(wget -qO - https://registry.hub.docker.com/v1/repositories/$DOCKER_REPOSITORY/tags | grep -Eo '(?:"name"\s*:\s*)"[^"]+"' | grep -Eo '"[^"]+"$' | grep -Eo '[^"]+');
  echo $DOCKER_TAGS;
  "
