version: 2

.build-script-template:
  default: &build-script
    - checkout
    - run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
        cmake --build .
        ctest -C Debug

jobs:
  build:
    steps: *build-script
    docker:
      - image: yudonguk/bicomc-docker:gcc-latest
      - image: yudonguk/bicomc-docker:gcc-7.2
      - image: yudonguk/bicomc-docker:gcc-6.4
      - image: yudonguk/bicomc-docker:gcc-5.5
      - image: yudonguk/bicomc-docker:gcc-4.9
      - image: yudonguk/bicomc-docker:gcc-4.8
      - image: yudonguk/bicomc-docker:gcc-4.6
      - image: yudonguk/bicomc-docker:gcc-4.4
      - image: yudonguk/bicomc-docker:clang-latest
      - image: yudonguk/bicomc-docker:clang-6.0
      - image: yudonguk/bicomc-docker:clang-5.0
      - image: yudonguk/bicomc-docker:clang-4.0
      - image: yudonguk/bicomc-docker:clang-3.8
      - image: yudonguk/bicomc-docker:clang-3.6
      - image: yudonguk/bicomc-docker:clang-3.4
